---
- name: Create nginx config file
  template:
    src: config
    dest: nginx.conf
- name: Start nginx
  docker_container:
    name: nginx
    image: nginx:1.17.9-alpine
    privileged: yes
    network_mode: host
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /var/log/nginx/access.log:/var/log/nginx/access.log
      - /var/log/nginx/error.log:/var/log/nginx/error.log  
    ports:
      - 80:80
      - 443:443