---
- name: Start grafana
  docker_container:
    name: "{{ grafana_cont_name }}"
    image: roboteam/rpa_dashboard_grafana
    pull: yes
    network_mode: host
    restart_policy: unless-stopped 
    volumes:
      - "{{ grafana_volume_name }}:/var/lib/grafana"
    env_file: docker.env
    ports:
      - 3000:3000
      