---
- name: Create jenkin-api-token
  file: 
    path: jenkins-api-token
    state: touch
- name: Start backend
  docker_container:
    name: "{{ backend_cont_name }}"
    image: roboteam/jenkins_service
    privileged: yes
    pull: yes
    network_mode: host
    env_file: docker.env
    volumes:
      - ./jenkins-api-token:/jenkins-api-token
      - ./certs:/certs
    ports:
      - 4000:4000