---
- name: Generate ssh-certificates
  shell: sh create_certs.sh 
  args:
    chdir: "certs"
    creates: robo.crt
- name: Create postgres volume
  docker_volume:
    name: database
- name: Create jenkins volume
  docker_volume:
    name: jenkins-data
- name: Create jenkins certificate volume
  docker_volume:
    name: jenkins-docker-certs
- name: Create grafana volume
  docker_volume:
    name: grafana-storage